/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rossi.devil.image;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Victor
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        buscaLocalCarregamento.setPreferredSize(carregaLocalImagem.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscaLocalCarregamento = new javax.swing.JDialog();
        carregaLocalImagem = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        lb_image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txCaminhoImage = new javax.swing.JTextField();
        btMudaImage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeFiles = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        subMenuLocalImagem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        buscaLocalCarregamento.setMaximumSize(new java.awt.Dimension(788, 372));
        buscaLocalCarregamento.setMinimumSize(new java.awt.Dimension(788, 372));
        buscaLocalCarregamento.setResizable(false);

        javax.swing.GroupLayout buscaLocalCarregamentoLayout = new javax.swing.GroupLayout(buscaLocalCarregamento.getContentPane());
        buscaLocalCarregamento.getContentPane().setLayout(buscaLocalCarregamentoLayout);
        buscaLocalCarregamentoLayout.setHorizontalGroup(
            buscaLocalCarregamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        buscaLocalCarregamentoLayout.setVerticalGroup(
            buscaLocalCarregamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        carregaLocalImagem.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        carregaLocalImagem.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        lb_image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Victor\\Downloads\\78596357_2498338013595877_1917373576751611904_n.jpg")); // NOI18N
        lb_image.setMaximumSize(new java.awt.Dimension(640, 640));
        lb_image.setPreferredSize(new java.awt.Dimension(640, 640));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        txCaminhoImage.setText("jTextField1");

        btMudaImage.setText("Muda Imagem");
        btMudaImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMudaImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txCaminhoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(btMudaImage)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCaminhoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMudaImage))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        alteraArvore();
        treeFiles.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeFilesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(treeFiles);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuArquivo.setText("Arquivos");

        subMenuLocalImagem.setText("Local das imagens");
        subMenuLocalImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuLocalImagemActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuLocalImagem);

        jMenuBar1.add(menuArquivo);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMudaImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMudaImageActionPerformed
        try {
            String nomeImagem = txCaminhoImage.getText();
            Imagem image = new Imagem();
            image.carregaImagem("C:\\Users\\Victor\\Downloads\\" + nomeImagem + ".jpg");
            lb_image.setIcon(image.geraImagemParaExibicao());
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMudaImageActionPerformed

    private void mudaImagemVisualizada(String imagemCaminho) {
        try {
            Imagem image = new Imagem();
            image.carregaImagem(imagemCaminho);
            lb_image.setIcon(image.geraImagemParaExibicao());
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void subMenuLocalImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuLocalImagemActionPerformed
        final int opcao = carregaLocalImagem.showOpenDialog(this);
        if (JFileChooser.APPROVE_OPTION == opcao) {
            pathEscolhido = carregaLocalImagem.getSelectedFile().getPath();
            carregaLocalImagem.setCurrentDirectory(new File(pathEscolhido));
        }
        final DefaultMutableTreeNode carregaArquivos = carregaArquivos(pathEscolhido);
        TreeModel l = new DefaultTreeModel(carregaArquivos);
        treeFiles.setModel(l);
    }//GEN-LAST:event_subMenuLocalImagemActionPerformed

    private void treeFilesValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeFilesValueChanged
        final TreePath selectionPath = treeFiles.getSelectionPath();
        final Object image = selectionPath.getPath()[1];
        final String imagemSelecionada = pathEscolhido+File.separatorChar+image.toString();
        System.out.println(imagemSelecionada);
        mudaImagemVisualizada(imagemSelecionada);
    }//GEN-LAST:event_treeFilesValueChanged

    public DefaultMutableTreeNode carregaArquivos(String src){
        File f = new File(src);
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(""+f.getName());
        for(File k:f.listFiles()){
            if(!k.isDirectory()){
                if(verificaSeImagem(k)){
                DefaultMutableTreeNode arquivo =new DefaultMutableTreeNode(""+k.getName());
                root.add(arquivo);
                }
            }
        }
        return root;
    }
    private void alteraArvore() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root:"+pathEscolhido);
        DefaultMutableTreeNode vegetableNode = new DefaultMutableTreeNode("Vegetables");
        DefaultMutableTreeNode fruitNode = new DefaultMutableTreeNode("Fruits");
        root.add(vegetableNode);
        root.add(fruitNode);
        treeFiles = new JTree(root);
    }
    String pathEscolhido="";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMudaImage;
    private javax.swing.JDialog buscaLocalCarregamento;
    private javax.swing.JFileChooser carregaLocalImagem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_image;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem subMenuLocalImagem;
    private javax.swing.JTree treeFiles;
    private javax.swing.JTextField txCaminhoImage;
    // End of variables declaration//GEN-END:variables

    private boolean verificaSeImagem(File k) {
        String name = k.getName().toLowerCase();
        if(name.contains(".jpg")){
            return true;
        }
        if(name.contains(".jpeg")){
            return true;
        }
        if(name.contains(".gif")){
            return true;
        }
        return false;
    }
}
