/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rossi.devil.image;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.ListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellEditor;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Victor
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        iconeDeArvoreDeArquivos();
        listaDeFavorito = new ListaDeFavorito(listLocalFavorito);
        iconeExibicao();
    }

    private void iconeExibicao() {
        try {
            final Imagem imagem = new Imagem();
            imagem.alteraDimensao(640, 640, getClass().getResource("/META-INF/Flag_.png"));
            lb_image.setIcon(imagem.geraImagemParaExibicao());
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void iconeDeArvoreDeArquivos() {
        Imagem imagem = new Imagem();

        final String src = "/META-INF/folder.png";
        final URL resource = getClass().getResource(src);
        imagem.alteraDimensao(20, 20, resource);
        try {
            final ImageIcon folderIcon = imagem.geraImagemParaExibicao();
            defineIconeArvore(src, treeFiles, folderIcon, folderIcon, null);
            defineIconeArvore(src, treeFavoritos, folderIcon, folderIcon, folderIcon);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void defineIconeArvore(String src, javax.swing.JTree tree, ImageIcon imageIconOpen, ImageIcon imageIconClose, ImageIcon imageIconLeaf) {
        DefaultTreeCellRenderer modeloArvore = new DefaultTreeCellRenderer();
        if (imageIconOpen != null) {
            modeloArvore.setOpenIcon(imageIconOpen);
        }
        if (imageIconClose != null) {
            modeloArvore.setClosedIcon(imageIconClose);
        }
        if (imageIconLeaf != null) {
            modeloArvore.setLeafIcon(imageIconLeaf);
        }
        tree.setCellRenderer(modeloArvore);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscaLocalSalvamento = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        txSalvaLocalFavorito = new javax.swing.JTextField();
        lbLocalFavorito = new javax.swing.JLabel();
        lbTitleSalvaLocalFavorito = new javax.swing.JLabel();
        btSalvaLocalFavorito = new javax.swing.JButton();
        btCancelaLocalFavorito = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        treeFavoritos = new javax.swing.JTree();
        carregaLocalImagem = new javax.swing.JFileChooser();
        localFavorito = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        lb_image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeFiles = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        listLocalFavorito = new javax.swing.JList<>();
        btMoverImagem = new javax.swing.JButton();
        btAdicionaLocal = new javax.swing.JButton();
        btRemoveLocal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        subMenuLocalImagem = new javax.swing.JMenuItem();
        menuDestino = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        buscaLocalSalvamento.setMaximumSize(new java.awt.Dimension(788, 372));
        buscaLocalSalvamento.setMinimumSize(new java.awt.Dimension(788, 372));
        buscaLocalSalvamento.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        txSalvaLocalFavorito.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txSalvaLocalFavorito.setText("jTextField1");

        lbLocalFavorito.setText("Novo Diretório:");

        lbTitleSalvaLocalFavorito.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTitleSalvaLocalFavorito.setText("Adicionar Local Favorito");

        btSalvaLocalFavorito.setText("Salvar");
        btSalvaLocalFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaLocalFavoritoActionPerformed(evt);
            }
        });

        btCancelaLocalFavorito.setText("Cancelar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btSalvaLocalFavorito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelaLocalFavorito))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitleSalvaLocalFavorito)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbLocalFavorito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txSalvaLocalFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitleSalvaLocalFavorito)
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocalFavorito)
                    .addComponent(txSalvaLocalFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvaLocalFavorito)
                    .addComponent(btCancelaLocalFavorito))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        jScrollPane2.setViewportView(treeFavoritos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout buscaLocalSalvamentoLayout = new javax.swing.GroupLayout(buscaLocalSalvamento.getContentPane());
        buscaLocalSalvamento.getContentPane().setLayout(buscaLocalSalvamentoLayout);
        buscaLocalSalvamentoLayout.setHorizontalGroup(
            buscaLocalSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscaLocalSalvamentoLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buscaLocalSalvamentoLayout.setVerticalGroup(
            buscaLocalSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        carregaLocalImagem.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        carregaLocalImagem.setCurrentDirectory(new java.io.File("C:\\Users\\Victor\\Desktop"));
        carregaLocalImagem.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        localFavorito.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        lb_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Flag_.png"))); // NOI18N
        lb_image.setMaximumSize(new java.awt.Dimension(640, 640));
        lb_image.setPreferredSize(new java.awt.Dimension(640, 640));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        treeFiles.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeFilesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(treeFiles);

        listLocalFavorito.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listLocalFavorito);

        btMoverImagem.setText("Mover Imagem");
        btMoverImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoverImagemActionPerformed(evt);
            }
        });

        btAdicionaLocal.setText("Adicionar Local");
        btAdicionaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionaLocalActionPerformed(evt);
            }
        });

        btRemoveLocal.setText("Remover Local");
        btRemoveLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveLocalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMoverImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAdicionaLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRemoveLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btMoverImagem)
                        .addGap(51, 51, 51)
                        .addComponent(btAdicionaLocal)
                        .addGap(18, 18, 18)
                        .addComponent(btRemoveLocal))
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuArquivo.setText("Arquivos");

        subMenuLocalImagem.setText("Carregar imagens");
        subMenuLocalImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuLocalImagemActionPerformed(evt);
            }
        });
        menuArquivo.add(subMenuLocalImagem);

        menuDestino.setText("Destino Imagem");
        menuDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDestinoActionPerformed(evt);
            }
        });
        menuArquivo.add(menuDestino);

        jMenuBar1.add(menuArquivo);

        jMenu2.setText("Configuração");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void subMenuLocalImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuLocalImagemActionPerformed
        final int opcao = carregaLocalImagem.showOpenDialog(this);
        if (JFileChooser.APPROVE_OPTION == opcao) {
            pathEscolhido = carregaLocalImagem.getSelectedFile().getPath();
            carregaLocalImagem.setCurrentDirectory(new File(pathEscolhido));
        }

        final DefaultMutableTreeNode carregaArquivos = new Arquivo().carregaDiretorio(pathEscolhido, true);
        TreeModel l = new DefaultTreeModel(carregaArquivos);
        treeFiles.setModel(l);
    }//GEN-LAST:event_subMenuLocalImagemActionPerformed

    private void treeFilesValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeFilesValueChanged
        final TreePath selectionPath = treeFiles.getSelectionPath();
        final Visualizador visualizador = new Visualizador(lb_image, pathEscolhido);
        if (visualizador.validaPathTree(selectionPath)) {
            return;
        }
        visualizador.alteraImagemNoVisualizador(selectionPath);
    }//GEN-LAST:event_treeFilesValueChanged

    private void btAdicionaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionaLocalActionPerformed
        buscaLocalSalvamento.setVisible(true);
        atualizaArvoreFavorito();
    }//GEN-LAST:event_btAdicionaLocalActionPerformed

    private void atualizaArvoreFavorito() {
        final DefaultMutableTreeNode carregaArquivos = new Arquivo().carregaDiretorio(pathFavorito, false);
        TreeModel l = new DefaultTreeModel(carregaArquivos);
        treeFavoritos.setModel(l);
    }

    private void menuDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDestinoActionPerformed
        int opcao = localFavorito.showOpenDialog(this);
        if (JFileChooser.APPROVE_OPTION == opcao) {
            pathFavorito = localFavorito.getSelectedFile().getPath();
            localFavorito.setCurrentDirectory(new File(pathFavorito));
        }
        listaDeFavorito.carregaArquivoConfiguracao(pathFavorito + File.separatorChar + "confFavorito.txt");
        listaDeFavorito.remontaLista();

    }//GEN-LAST:event_menuDestinoActionPerformed

    private void btSalvaLocalFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvaLocalFavoritoActionPerformed

        String localNovo = txSalvaLocalFavorito.getText();
        String[] ramoLocalNovo = new String[0];
        String reg = "<->";
        if (localNovo.contains("\\")) {
            localNovo = localNovo.replace("\\", "" + reg);
            ramoLocalNovo = localNovo.split("" + reg);
        } else if (localNovo.contains("/")) {
            localNovo = localNovo.replace("/", "" + reg);
            ramoLocalNovo = localNovo.split("" + reg);
        } else {
            ramoLocalNovo = new String[]{localNovo};
        }
        final Diretorio diretorio = new Diretorio(pathFavorito);
        listaDeFavorito.adicionaLocalNovoAoFavorito(diretorio.criaDiretorio(new Diretorio(pathFavorito).montaPath(treeFavoritos.getSelectionPath()), ramoLocalNovo));
        listaDeFavorito.remontaLista();
        listaDeFavorito.gravaArquivo(pathFavorito + File.separatorChar + "confFavorito.txt");
        atualizaArvoreFavorito();
    }//GEN-LAST:event_btSalvaLocalFavoritoActionPerformed

    private void btMoverImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoverImagemActionPerformed
        final TreePath selectionPath = treeFiles.getSelectionPath();
        System.out.println("Path Home     Selecionado:" + new Diretorio(pathEscolhido).montaPathDaImagemSelecionada(selectionPath));
        System.out.println("Path Destinho Selecionado:" + pathFavorito + listLocalFavorito.getSelectedValue());
        File origem = new File(new Diretorio(pathEscolhido).montaPathDaImagemSelecionada(selectionPath));
        if (origem.isFile()) {
            try {
                Files.copy(Paths.get(new Diretorio(pathEscolhido).montaPathDaImagemSelecionada(selectionPath)), Paths.get(pathFavorito + listLocalFavorito.getSelectedValue() + Diretorio.imagemSelecionada(selectionPath)), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btMoverImagemActionPerformed

    private void btRemoveLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveLocalActionPerformed
        listaDeFavorito.remontaLista();
    }//GEN-LAST:event_btRemoveLocalActionPerformed

    private String pathEscolhido = "";
    private String pathFavorito = "";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionaLocal;
    private javax.swing.JButton btCancelaLocalFavorito;
    private javax.swing.JButton btMoverImagem;
    private javax.swing.JButton btRemoveLocal;
    private javax.swing.JButton btSalvaLocalFavorito;
    private javax.swing.JDialog buscaLocalSalvamento;
    private javax.swing.JFileChooser carregaLocalImagem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbLocalFavorito;
    private javax.swing.JLabel lbTitleSalvaLocalFavorito;
    private javax.swing.JLabel lb_image;
    private javax.swing.JList<String> listLocalFavorito;
    private javax.swing.JFileChooser localFavorito;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuDestino;
    private javax.swing.JMenuItem subMenuLocalImagem;
    private javax.swing.JTree treeFavoritos;
    private javax.swing.JTree treeFiles;
    private javax.swing.JTextField txSalvaLocalFavorito;
    // End of variables declaration//GEN-END:variables
    private ListaDeFavorito listaDeFavorito;
}
